"""data consents and athlete sex

Revision ID: ac21c68cd531
Revises: ab6839934c22
Create Date: 2026-08-08 14:37:50.170312

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ac21c68cd531'
down_revision: str | None = 'ab6839934c22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('audience', sa.String(length=8), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_active', 'data_consents', ['athlete_id', 'scope', 'revoked_at'], unique=False)
    op.create_index('ix_consent_athlete_scope', 'data_consents', ['athlete_id', 'scope'], unique=False)
    op.create_index(op.f('ix_data_consents_athlete_id'), 'data_consents', ['athlete_id'], unique=False)
    # server_default обязателен: колонка NOT NULL, а профили уже существуют.
    # После заполнения дефолт снимаем — значение задаёт приложение, не БД.
    op.add_column(
        'athlete_profiles',
        sa.Column('sex', sa.String(length=16), nullable=False, server_default='not_specified'),
    )
    op.alter_column('athlete_profiles', 'sex', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'sex')
    op.drop_index(op.f('ix_data_consents_athlete_id'), table_name='data_consents')
    op.drop_index('ix_consent_athlete_scope', table_name='data_consents')
    op.drop_index('ix_consent_active', table_name='data_consents')
    op.drop_table('data_consents')
    # ### end Alembic commands ###
