"""dashboard aggregates: daily performance, structured injury location

Revision ID: ab6839934c22
Revises: 7362971c1808
Create Date: 2026-08-07 16:02:27.798360

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ab6839934c22'
down_revision: str | None = '7362971c1808'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('daily_performance', sa.Float(), nullable=True))
    op.add_column('injury_records', sa.Column('body_region', sa.String(length=16), nullable=True))
    op.add_column('injury_records', sa.Column('body_side', sa.String(length=8), nullable=True))
    op.add_column('injury_records', sa.Column('injury_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('injury_records', 'injury_type')
    op.drop_column('injury_records', 'body_side')
    op.drop_column('injury_records', 'body_region')
    op.drop_column('daily_metrics', 'daily_performance')
    # ### end Alembic commands ###
