"""off barcode partial unique index

Revision ID: 0de9bdb1fb60
Revises: c4a977f367ca
Create Date: 2026-08-31 15:39:40.657765

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0de9bdb1fb60'
down_revision: str | None = 'c4a977f367ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_food_items_off_barcode', 'food_items', ['barcode'], unique=True, postgresql_where=sa.text("source = 'open_food_facts' AND barcode IS NOT NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_food_items_off_barcode', table_name='food_items', postgresql_where=sa.text("source = 'open_food_facts' AND barcode IS NOT NULL"))
    # ### end Alembic commands ###
