"""nutrition diary

Revision ID: e82d52245f2f
Revises: 43a396a23407
Create Date: 2026-08-08 15:21:56.647082

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e82d52245f2f'
down_revision: str | None = '43a396a23407'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=False),
    sa.Column('carbs_100g', sa.Float(), nullable=False),
    sa.Column('fiber_100g', sa.Float(), nullable=True),
    sa.Column('serving_size_g', sa.Float(), nullable=True),
    sa.Column('serving_name', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_items_barcode', 'food_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_food_items_created_by'), 'food_items', ['created_by'], unique=False)
    op.create_index('ix_food_items_name', 'food_items', ['name'], unique=False)
    op.create_table('nutrition_targets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_nutrition_target_user')
    )
    op.create_table('food_log_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(length=16), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_log_athlete_date', 'food_log_entries', ['athlete_id', 'date'], unique=False)
    op.create_index(op.f('ix_food_log_entries_athlete_id'), 'food_log_entries', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_food_log_entries_date'), 'food_log_entries', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_log_entries_date'), table_name='food_log_entries')
    op.drop_index(op.f('ix_food_log_entries_athlete_id'), table_name='food_log_entries')
    op.drop_index('ix_food_log_athlete_date', table_name='food_log_entries')
    op.drop_table('food_log_entries')
    op.drop_table('nutrition_targets')
    op.drop_index('ix_food_items_name', table_name='food_items')
    op.drop_index(op.f('ix_food_items_created_by'), table_name='food_items')
    op.drop_index('ix_food_items_barcode', table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
