"""onboarding_policy_consent

Revision ID: 69f0c8d7ffb8
Revises: a755e3ca6e0d
Create Date: 2026-09-03 17:14:03.920806

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '69f0c8d7ffb8'
down_revision: str | None = 'a755e3ca6e0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_consent_active', 'policy_consents', ['user_id', 'kind', 'revoked_at'], unique=False)
    op.create_index('ix_policy_consent_user_kind', 'policy_consents', ['user_id', 'kind'], unique=False)
    op.create_index(op.f('ix_policy_consents_user_id'), 'policy_consents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_consents_user_id'), table_name='policy_consents')
    op.drop_index('ix_policy_consent_user_kind', table_name='policy_consents')
    op.drop_index('ix_policy_consent_active', table_name='policy_consents')
    op.drop_table('policy_consents')
    # ### end Alembic commands ###
