"""user full name parts

Revision ID: 69a9be34165f
Revises: 733e9f081260
Create Date: 2026-08-10 19:55:44.084101

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '69a9be34165f'
down_revision: str | None = '733e9f081260'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: колонки NOT NULL, а пользователи уже есть.
    # После бэкфилла дефолт снимаем — значение задаёт приложение, не БД.
    for column in ('last_name', 'first_name', 'middle_name'):
        op.add_column(
            'users', sa.Column(column, sa.String(length=128), nullable=False, server_default='')
        )

    # Раскладываем прежний свободный name: одно слово — это имя (онбординг спрашивал
    # «Как тебя зовут?»), несколько — ФИО из приглашения в порядке Фамилия Имя Отчество.
    op.execute(
        """
        UPDATE users
        SET last_name = CASE WHEN src.n LIKE '% %' THEN split_part(src.n, ' ', 1) ELSE '' END,
            first_name = CASE WHEN src.n LIKE '% %' THEN split_part(src.n, ' ', 2) ELSE src.n END,
            middle_name = CASE WHEN src.n LIKE '% %' THEN split_part(src.n, ' ', 3) ELSE '' END
        FROM (SELECT id, regexp_replace(btrim(name), '\\s+', ' ', 'g') AS n FROM users) AS src
        WHERE users.id = src.id
        """
    )
    for column in ('last_name', 'first_name', 'middle_name'):
        op.alter_column('users', column, server_default=None)

    # Свободный name больше не хранится: строку «Фамилия Имя» для списков
    # собирает приложение (app.models.user.display_name)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))
    op.execute("UPDATE users SET name = btrim(last_name || ' ' || first_name)")
    op.alter_column('users', 'name', server_default=None)

    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
