"""wellness pain map, injury and symptom details

Revision ID: 7362971c1808
Revises: 29808c360e1a
Create Date: 2026-08-07 01:06:03.399090

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7362971c1808'
down_revision: str | None = '29808c360e1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_entries', sa.Column('injury_area', sa.String(length=16), nullable=True))
    op.add_column('wellness_entries', sa.Column('injury_type', sa.String(length=16), nullable=True))
    op.add_column('wellness_entries', sa.Column('symptom_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness_entries', 'symptom_type')
    op.drop_column('wellness_entries', 'injury_type')
    op.drop_column('wellness_entries', 'injury_area')
    # ### end Alembic commands ###
