"""rpe one entry per session

Revision ID: c4a977f367ca
Revises: 69a9be34165f
Create Date: 2026-08-10 20:17:49.821730

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c4a977f367ca'
down_revision: str | None = '69a9be34165f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Одна оценка на сессию. Свободный RPE (event_id = NULL) под ограничение не попадает.
    op.create_index(
        'uq_rpe_athlete_event',
        'rpe_entries',
        ['athlete_id', 'event_id'],
        unique=True,
        postgresql_where=sa.text('event_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_rpe_athlete_event',
        table_name='rpe_entries',
        postgresql_where=sa.text('event_id IS NOT NULL'),
    )
    # ### end Alembic commands ###
