"""organization branding

Revision ID: a755e3ca6e0d
Revises: 0de9bdb1fb60
Create Date: 2026-09-02 22:47:16.091061

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a755e3ca6e0d'
down_revision: str | None = '0de9bdb1fb60'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Тема организации: 1:1 с организацией, отсутствие строки = тема продукта.
    op.create_table('organization_branding',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tokens', sa.JSON(), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_branding')
    # ### end Alembic commands ###
