"""food category and custom kind

Revision ID: 733e9f081260
Revises: e82d52245f2f
Create Date: 2026-08-08 15:43:53.140530

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '733e9f081260'
down_revision: str | None = 'e82d52245f2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: колонка NOT NULL, а продукты в справочнике уже есть.
    # После заполнения дефолт снимаем — значение задаёт приложение, не БД.
    op.add_column(
        'food_items',
        sa.Column('category', sa.String(length=16), nullable=False, server_default='other'),
    )
    op.alter_column('food_items', 'category', server_default=None)
    op.add_column('food_items', sa.Column('custom_kind', sa.String(length=16), nullable=True))


def downgrade() -> None:
    op.drop_column('food_items', 'custom_kind')
    op.drop_column('food_items', 'category')
    # ### end Alembic commands ###
