"""menstrual cycle tracking

Revision ID: 43a396a23407
Revises: ac21c68cd531
Create Date: 2026-08-08 15:07:28.516110

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '43a396a23407'
down_revision: str | None = 'ac21c68cd531'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_start', sa.Boolean(), nullable=False),
    sa.Column('period_end', sa.Boolean(), nullable=False),
    sa.Column('flow', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'date', name='uq_cycle_athlete_date')
    )
    op.create_index(op.f('ix_cycle_logs_athlete_id'), 'cycle_logs', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_cycle_logs_date'), 'cycle_logs', ['date'], unique=False)
    op.create_table('cycle_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('average_cycle_length', sa.Integer(), nullable=False),
    sa.Column('average_period_length', sa.Integer(), nullable=False),
    sa.Column('contraception', sa.String(length=24), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('cycle_symptom_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('symptom', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['cycle_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_symptom_logs_log_id'), 'cycle_symptom_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cycle_symptom_logs_log_id'), table_name='cycle_symptom_logs')
    op.drop_table('cycle_symptom_logs')
    op.drop_table('cycle_settings')
    op.drop_index(op.f('ix_cycle_logs_date'), table_name='cycle_logs')
    op.drop_index(op.f('ix_cycle_logs_athlete_id'), table_name='cycle_logs')
    op.drop_table('cycle_logs')
    # ### end Alembic commands ###
